[project]
name = "explicit-effects"
version = "0.1.0"
description = "Prototype of a side-effect analysis using explicit values in a Static Single Use IR"
readme = "README.md"
authors = [
    { name = "Samuel Malec" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
graal2ct = "graal2ct.__main__:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["cthu", "effects", "graal", "graal2ct", "rules"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["test"]
python_files = ["check_*.py"]
python_functions = ["check_*"]
